booktest/urls.py
from django.conf.urls import url
from booktest import views

urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^([a-zA-Z]+)/(\d+)$',views.show, name='show'),
    url(r'^index2$', views.index2, name='index2'),
    url(r'^user1', views.user1, name='user1'),
    url(r'^user2', views.user2, name='user2'),
    url(r'^htmlTest', views.htmlTest, name='htmlTest'),
    url(r'^csrf1', views.csrf1, name='csrf1'),
    url(r'^csrf2', views.csrf2, name='csrf2'),
    url(r'^verifyCode', views.verifyCode, name='virifyCode'),
    url(r'^verifyTest1', views.verifyTest1, name='vertifyTest1'),
    url(r'^verifyTest2', views.verifyTest2, name='vertifyTest2'),
]

test4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('booktest.urls', namespace='booktest'))
]

booktest/models.py
from django.db import models

class BookInfo(models.Model):
    btitle=models.CharField(max_length=20)
    bpub_date=models.DateTimeField()

    def __str__(self):
        return self.btitle

    class Meta:
        db_table = 'bookinfo'

    # books1 = models.Manager()
    # books2 = BookInfoManager()

class HeroInfo(models.Model):
    hname=models.CharField(max_length=10)
    hgender=models.BooleanField()
    hcontent=models.CharField(max_length=1000)
    hbook=models.ForeignKey(BookInfo)

    def showname(self):
        return self.hname
    def __str__(self):
        return self.hname

booktest/views.py
#coding=utf-8
from django.http import HttpResponse
from django.shortcuts import render
from .models import *

# Create your views here.
def index(request):
    # hero = HeroInfo.objects.get(pk=2)
    # context = {'hero':hero}

    # list = HeroInfo.objects.filter(hname='ff')
    list = HeroInfo.objects.all()
    context = {'list':list}
    return render(request, 'booktest/index.html',context)

def show(request,text, id):
    context = {'text':text,'id':id}
    return render(request, 'booktest/show.html', context)

#用于练习模板的继承
def index2(request):
    return render(request, 'booktest/indexExtendBase.html')

def user1(request):
    return render(request, 'booktest/user1.html')

def user2(request):
    return render(request, 'booktest/user2.html')


#html转义
def htmlTest(request):
    context={'t1':'<h1>123</h1>'}
    return render(request,'booktest/htmlTest.html',context)

#csrf
def csrf1(request):
    return render(request, 'booktest/csrf1.html')

def csrf2(request):
    uname = request.POST['uname']
    return HttpResponse(uname)

#验证码
def verifyCode(request):
    from PIL import Image, ImageDraw, ImageFont
    import random
    #创建背景色
    bgColor = (random.randrange(50,100),random.randrange(0,50),random.randrange(0,90))
    #规定宽高
    width = 100
    height = 25
    #创建画布
    image = Image.new('RGB',(width,height),bgColor)
    #构造字体对象
    font = ImageFont.truetype('Arial.ttf', 24)
    #创建画笔
    draw = ImageDraw.Draw(image)
    #创建文本内容
    text = '0123ABCD'
    # 逐个绘制字符
    textTemp = ''
    for i in range(4):
        textTemp1 = text[random.randrange(0,len(text))]
        textTemp += textTemp1
        draw.text((i*25,0),
                  textTemp1,
                  (255, 255, 255),
                  font)
    request.session['code'] = textTemp
    #保存到内存流中
    import io
    buf = io.BytesIO()
    image.save(buf,'png')
    #将内存流中的内容输出到客户端
    return HttpResponse(buf.getvalue(), 'image/png')

def verifyTest1(request):
    return render(request, 'booktest/verifyTest1.html')

def verifyTest2(request):
    code1 = request.POST['code1']
    code2 = request.session['code']
    if code1==code2:
        return HttpResponse('ok')
    else:
        return HttpResponse('no')

templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block head %}{% endblock %}
</head>
<body>
<h1>logo</h1>
<hr>
{% block content1 %}
    <h1>abc</h1>
{% endblock %}
<hr>
<h1>contact</h1>
</body>
</html>

templates/booktest/base_goods.html
{% extends 'booktest/base.html' %}

templates/booktest/base_user.html
{% extends 'booktest/base.html' %}
{% block content1 %}
<table border="1">
<tr>
    <td height="300">用户导航</td>
    <td>{% block user_content %}{% endblock %}</td>
</tr>
</table>
{% endblock content1 %}

templates/booktest/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="csrf2" method="post">
    {% csrf_token %}
    <input type="text" name="uname">
    <input type="submit" value="提价">
</form>
</body>
</html>

templates/booktest/csrf2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/booktest/htmlTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ t1 }}
<hr>
{{ t1|safe }}
<hr>
{% autoescape off %}
{{ t1 }}
{% endautoescape %}
<hr>
字面值：<br>
{{ t2|default:'<b>abc</b>' }}
<br>
手动转义：{{ t2|default:'&lt;h1&gt;abc&lt;/h1&gt;' }}
</body>
</html>

templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'booktest:show' 'mall' '456'%}">显示</a>
{% comment %}
{{ hero.showname }}
{% endcomment %}
{% for hero in list%}
    {% if forloop.counter|divisibleby:'2' %}
    <li style="color: red">{{ forloop.counter }}:{{ hero.showname }}</li>
    {% else %}
    <li style="color: blue">{{ forloop.counter }}:{{ hero.showname }}</li>
    {% endif %}
{% empty %}
    没有东西
{% endfor %}
</body>
</html>

templates/booktest/indexExtendBase.html
{% extends 'booktest/base.html' %}

{% block content1 %}
<h1>123</h1>
{% endblock content1 %}

templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ text }}
{{ id }}
{#{% for num in ids %}#}
{#    {{ num }}#}
{#{% endfor %}#}
</body>
</html>

templates/booktest/user1.html
{% extends 'booktest/base_user.html' %}

{% block head %}
<script>alert('123')</script>
{% endblock head %}

{% block user_content %}
    <h1>用户中心1</h1>
{% endblock user_content %}

templates/booktest/user2.html
{% extends 'booktest/base_user.html' %}
{% block user_content %}
    <h1>用户中心2</h1>
{% endblock user_content %}

templates/booktest/verifyTest1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="verifyTest2" method="post">
    {% csrf_token %}
    <input type="text" name="code1">
    <img src="verifyCode">
    <input type="submit" value="提交">
</form>
</body>
</html>